# Create dictionaries for looking up VLCB codes and return a useful description.
# Use the vlcbdefs.csv

INPUT=../VLCB-defs/vlcb-defs.csv
OUTPUT=vlcbdictionaries.py

# first out put the header stuff
cat << EOF > $OUTPUT
# DO NOT EDIT THIS FILE.
# This file is automatically generated by $0 from vlcb-defs.csv
#

EOF
# Set input field separator (IFS) to comma and carriage return for running on Windows.
while IFS=$',\r' read type name value comment 
do
    if [ "$type" = "comment" ]
    then
        echo -e "# $name\t$value\t$comment"
    elif [ -z "$type" ]
    then
        :
    else
        type=${type/#Cbus/Vlcb}
        if [ "$type" != "$prevType" ]
        then
            if [ -n "$prevType" ]
            then
                echo "}"
                echo ""
            fi
            echo "$type = {"
            prevType=$type
        fi
        if [ "X$name" = "X" ]
        then
            echo -e "  # $value$comment" 
        else
            if [ -n "$comment" ]
            then
                comment=" # $comment"
            fi
            name=$(echo "$name" | sed 's/[^_]*_//')

            echo -e "  $value : \"$name\",$comment"
        fi
    fi
done < $INPUT >>$OUTPUT

if [ -n "prevType" ]
then
    echo "}" >>$OUTPUT
    echo ""   >>$OUTPUT
fi
